In [3]:
!pip install pandas

Collecting pandas
  Using cached pandas-2.3.3-cp310-cp310-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (12.8 MB)
Collecting tzdata>=2022.7
  Using cached tzdata-2026.1-py2.py3-none-any.whl (348 kB)
Requirement already satisfied: numpy>=1.22.4 in /home/mvhoang/Desktop/AI in Action/day8/venv/lib/python3.10/site-packages (from pandas) (2.2.6)
Collecting pytz>=2020.1
  Using cached pytz-2026.1.post1-py2.py3-none-any.whl (510 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/mvhoang/Desktop/AI in Action/day8/venv/lib/python3.10/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/mvhoang/Desktop/AI in Action/day8/venv/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Installing collected packages: pytz, tzdata, pandas
Successfully installed pandas-2.3.3 pytz-2026.1.post1 tzdata-2026.1

In [5]:
import chromadb
import pandas as pd

# Bỏ giới hạn hiển thị pandas
pd.set_option('display.max_rows', None)        # hiện hết rows
pd.set_option('display.max_columns', None)     # hiện hết columns
pd.set_option('display.max_colwidth', None)    # hiện hết text trong cell
pd.set_option('display.width', None)           # không wrap dòng

In [6]:
client = chromadb.PersistentClient(path="chroma_db")
col = client.get_collection("rag_lab")

results = col.get(include=["documents", "metadatas"])

df = pd.DataFrame(results["metadatas"])
df["text"] = results["documents"]
df["chunk_id"] = results["ids"]

# Sắp xếp cột cho dễ đọc
df = df[["chunk_id", "source", "department", "section", "effective_date", "access", "text"]]
df

,chunk_id,source,department,section,effective_date,access,text
0,hr_leave_policy_0,hr/leave-policy-2026.pdf,HR,Phần 1: Các loại nghỉ phép,2026-01-01,internal,1.1 Nghỉ phép năm (Annual Leave):\n- Số ngày: 12 ngày/năm cho nhân viên dưới 3 năm kinh nghiệm.\n- Số ngày: 15 ngày/năm cho nhân viên từ 3-5 năm kinh nghiệm.\n- Số ngày: 18 ngày/năm cho nhân viên trên 5 năm kinh nghiệm.\n- Chuyển năm sau: Tối đa 5 ngày phép năm chưa dùng được chuyển sang năm tiếp theo.\n\n1.2 Nghỉ ốm (Sick Leave):\n- Số ngày: 10 ngày/năm có trả lương.\n- Yêu cầu: Thông báo cho Line Manager trước 9:00 sáng ngày nghỉ.\n- Nếu nghỉ trên 3 ngày liên tiếp: Cần giấy tờ y tế từ bệnh viện.\n\n1.3 Nghỉ thai sản:\n- Nghỉ sinh con: 6 tháng theo quy định Luật Lao động.\n- Nghỉ nuôi con nhỏ: 1 tiếng/ngày trong 12 tháng đầu sau sinh.\n\n1.4 Nghỉ lễ tết:\nTheo lịch nghỉ lễ quốc gia do HR công bố hàng năm vào tháng 12.
1,hr_leave_policy_1,hr/leave-policy-2026.pdf,HR,Phần 2: Quy trình xin nghỉ phép,2026-01-01,internal,Bước 1: Nhân viên gửi yêu cầu nghỉ phép qua hệ thống HR Portal (https://hr.company.internal) ít nhất 3 ngày làm việc trước ngày nghỉ.\nBước 2: Line Manager phê duyệt hoặc từ chối trong vòng 1 ngày làm việc.\nBước 3: Nhân viên nhận thông báo qua email sau khi được phê duyệt.\n\nTrường hợp khẩn cấp: Có thể gửi yêu cầu muộn hơn nhưng phải được Line Manager đồng ý qua tin nhắn trực tiếp.
2,hr_leave_policy_2,hr/leave-policy-2026.pdf,HR,Phần 3: Chính sách làm thêm giờ,2026-01-01,internal,3.1 Điều kiện làm thêm:\nLàm thêm giờ phải được Line Manager phê duyệt trước bằng văn bản.\n\n3.2 Hệ số lương làm thêm:\n- Ngày thường: 150% lương giờ tiêu chuẩn.\n- Ngày cuối tuần: 200% lương giờ tiêu chuẩn.\n- Ngày lễ: 300% lương giờ tiêu chuẩn.
3,hr_leave_policy_3,hr/leave-policy-2026.pdf,HR,Phần 4: Remote work policy,2026-01-01,internal,4.1 Điều kiện remote:\n- Nhân viên sau probation period có thể làm remote tối đa 2 ngày/tuần.\n- Team Lead phải phê duyệt lịch remote qua HR Portal.\n- Ngày onsite bắt buộc: Thứ 3 và Thứ 5 theo lịch team.\n\n4.2 Yêu cầu kỹ thuật khi remote:\n- Kết nối VPN bắt buộc khi làm việc với hệ thống nội bộ.\n- Camera bật trong các cuộc họp team.
4,hr_leave_policy_4,hr/leave-policy-2026.pdf,HR,Phần 5: Liên hệ HR,2026-01-01,internal,"Email: hr@company.internal\nHotline: ext. 2000\nHR Portal: https://hr.company.internal\nGiờ làm việc: Thứ 2 - Thứ 6, 8:30 - 17:30"
5,access_control_sop_0,it/access-control-sop.md,IT Security,Section 1: Phạm vi và mục đích,2026-01-01,internal,"Tài liệu này quy định quy trình cấp phép truy cập vào các hệ thống nội bộ của công ty.\nÁp dụng cho tất cả nhân viên, contractor, và third-party vendor."
6,access_control_sop_1,it/access-control-sop.md,IT Security,Section 2: Phân cấp quyền truy cập,2026-01-01,internal,"Level 1 — Read Only:\nÁp dụng cho: Tất cả nhân viên mới trong 30 ngày đầu.\nPhê duyệt: Line Manager.\nThời gian xử lý: 1 ngày làm việc.\n\nLevel 2 — Standard Access:\nÁp dụng cho: Nhân viên chính thức đã qua thử việc.\nPhê duyệt: Line Manager + IT Admin.\nThời gian xử lý: 2 ngày làm việc.\n\nLevel 3 — Elevated Access:\nÁp dụng cho: Team Lead, Senior Engineer, Manager.\nPhê duyệt: Line Manager + IT Admin + IT Security.\nThời gian xử lý: 3 ngày làm việc.\n\nLevel 4 — Admin Access:\nÁp dụng cho: DevOps, SRE, IT Admin.\nPhê duyệt: IT Manager + CISO.\nThời gian xử lý: 5 ngày làm việc.\nYêu cầu thêm: Training bắt buộc về security policy."
7,access_control_sop_2,it/access-control-sop.md,IT Security,Section 3: Quy trình yêu cầu cấp quyền,2026-01-01,internal,Bước 1: Nhân viên tạo Access Request ticket trên Jira (project IT-ACCESS).\nBước 2: Line Manager phê duyệt yêu cầu trong 1 ngày làm việc.\nBước 3: IT Admin kiểm tra compliance và cấp quyền.\nBước 4: IT Security review với Level 3 và Level 4.\nBước 5: Nhân viên nhận thông báo qua email khi quyền được cấp.
8,access_control_sop_3,it/access-control-sop.md,IT Security,Section 4: Escalation khi cần thay đổi quyền hệ thống,2026-01-01,internal,"Escalation chỉ áp dụng khi cần thay đổi quyền hệ thống ngoài quy trình thông thường.\nVí dụ: Khẩn cấp trong sự cố P1, cần cấp quyền tạm thời để fix incident.\n\nQuy trình escalation khẩn cấp:\n1. On-call IT Admin có thể cấp quyền tạm thời (max 24 giờ) sau khi được Tech Lead phê duyệt bằng lời.\n2. Sau 24 giờ, phải có ticket chính thức hoặc quyền bị thu hồi tự động.\n3. Mọi quyền tạm thời phải được ghi log vào hệ thống Security Audit."
9,access_control_sop_4,it/access-control-sop.md,IT Security,Section 5: Thu hồi quyền truy cập,2026-01-01,internal,Quyền phải được thu hồi trong các trường hợp:\n- Nhân viên nghỉ việc: Thu hồi ngay trong ngày cuối.\n- Hết hạn contract: Thu hồi đúng ngày hết hạn.\n- Chuyển bộ phận: Điều chỉnh trong 3 ngày làm việc.
10,access_control_sop_5,it/access-control-sop.md,IT Security,Section 6: Audit và review định kỳ,2026-01-01,internal,IT Security thực hiện access review mỗi 6 tháng.\nMọi bất thường phải được báo cáo lên CISO trong vòng 24 giờ.
11,access_control_sop_6,it/access-control-sop.md,IT Security,Section 7: Công cụ liên quan,2026-01-01,internal,Ticket system: Jira (project IT-ACCESS)\nIAM system: Okta\nAudit log: Splunk\nEmail: it-access@company.internal
12,sla_p1_2026_0,support/sla-p1-2026.pdf,IT,Phần 1: Định nghĩa mức độ ưu tiên,2026-01-15,internal,"P1 — CRITICAL (Khẩn cấp):\nĐịnh nghĩa: Sự cố ảnh hưởng toàn bộ hệ thống production, không có workaround.\nVí dụ: Database sập, API gateway down, toàn bộ người dùng không thể đăng nhập.\n\nP2 — HIGH (Nghiêm trọng):\nĐịnh nghĩa: Sự cố ảnh hưởng một phần hệ thống, có workaround tạm thời.\nVí dụ: Một số tính năng không hoạt động, ảnh hưởng một nhóm người dùng.\n\nP3 — MEDIUM (Trung bình):\nĐịnh nghĩa: Lỗi ảnh hưởng không đáng kể, người dùng vẫn làm việc được.\n\nP4 — LOW (Thấp):\nĐịnh nghĩa: Yêu cầu cải tiến, gợi ý, hoặc lỗi giao diện nhỏ."
13,sla_p1_2026_1,support/sla-p1-2026.pdf,IT,Phần 2: SLA theo mức độ ưu tiên,2026-01-15,internal,"Ticket P1:\n- Phản hồi ban đầu (first response): 15 phút kể từ khi ticket được tạo.\n- Xử lý và khắc phục (resolution): 4 giờ.\n- Escalation: Tự động escalate lên Senior Engineer nếu không có phản hồi trong 10 phút.\n- Thông báo stakeholder: Ngay khi nhận ticket, update mỗi 30 phút cho đến khi resolve.\n\nTicket P2:\n- Phản hồi ban đầu: 2 giờ.\n- Xử lý và khắc phục: 1 ngày làm việc.\n- Escalation: Tự động escalate sau 90 phút không có phản hồi.\n\nTicket P3:\n- Phản hồi ban đầu: 1 ngày làm việc.\n- Xử lý và khắc phục: 5 ngày làm việc.\n\nTicket P4:\n- Phản hồi ban đầu: 3 ngày làm việc.\n- Xử lý và khắc phục: Theo sprint cycle (thông thường 2-4 tuần)."
14,sla_p1_2026_2,support/sla-p1-2026.pdf,IT,Phần 3: Quy trình xử lý sự cố P1,2026-01-15,internal,"Bước 1: Tiếp nhận\nOn-call engineer nhận alert hoặc ticket, xác nhận severity trong 5 phút.\n\nBước 2: Thông báo\nGửi thông báo tới Slack #incident-p1 và email incident@company.internal ngay lập tức.\n\nBước 3: Triage và phân công\nLead Engineer phân công engineer xử lý trong 10 phút.\n\nBước 4: Xử lý\nEngineer cập nhật tiến độ lên ticket mỗi 30 phút. Nếu cần hỗ trợ thêm, escalate ngay.\n\nBước 5: Resolution\nSau khi khắc phục, viết incident report trong vòng 24 giờ."
15,sla_p1_2026_3,support/sla-p1-2026.pdf,IT,Phần 4: Công cụ và kênh liên lạc,2026-01-15,internal,"Ticket system: Jira (project IT-SUPPORT)\nSlack channel: #incident-p1, #incident-p2\nPagerDuty: Tự động nhắn on-call khi P1 ticket mới\nHotline on-call: ext. 9999 (24/7)"
16,sla_p1_2026_4,support/sla-p1-2026.pdf,IT,Phần 5: Lịch sử phiên bản,2026-01-15,internal,v2026.1 (2026-01-15): Cập nhật SLA P1 resolution từ 6 giờ xuống 4 giờ.\nv2025.3 (2025-09-01): Thêm quy trình escalation tự động.\nv2025.1 (2025-03-01): Phiên bản đầu tiên.
17,it_helpdesk_faq_0,support/helpdesk-faq.md,IT,Section 1: Tài khoản và mật khẩu,2026-01-20,internal,"Q: Tôi quên mật khẩu, phải làm gì?\nA: Truy cập https://sso.company.internal/reset hoặc liên hệ Helpdesk qua ext. 9000. Mật khẩu mới sẽ được gửi qua email công ty trong vòng 5 phút.\n\nQ: Tài khoản bị khóa sau bao nhiêu lần đăng nhập sai?\nA: Tài khoản bị khóa sau 5 lần đăng nhập sai liên tiếp. Để mở khóa, liên hệ IT Helpdesk hoặc tự reset qua portal SSO.\n\nQ: Mật khẩu cần thay đổi định kỳ không?\nA: Có. Mật khẩu phải được thay đổi mỗi 90 ngày. Hệ thống sẽ nhắc nhở 7 ngày trước khi hết hạn."
18,it_helpdesk_faq_1,support/helpdesk-faq.md,IT,Section 2: VPN và kết nối từ xa,2026-01-20,internal,"Q: Phần mềm VPN nào công ty dùng?\nA: Công ty sử dụng Cisco AnyConnect. Download tại https://vpn.company.internal/download.\n\nQ: Tôi bị mất kết nối VPN liên tục, phải làm gì?\nA: Kiểm tra kết nối Internet trước. Nếu vẫn lỗi, tạo ticket P3 với log file VPN đính kèm.\n\nQ: VPN có giới hạn số thiết bị không?\nA: Mỗi tài khoản được kết nối VPN trên tối đa 2 thiết bị cùng lúc."
19,it_helpdesk_faq_2,support/helpdesk-faq.md,IT,Section 3: Phần mềm và license,2026-01-20,internal,"Q: Tôi cần cài phần mềm mới, phải làm gì?\nA: Gửi yêu cầu qua Jira project IT-SOFTWARE. Line Manager phải phê duyệt trước khi IT cài đặt.\n\nQ: Ai chịu trách nhiệm gia hạn license phần mềm?\nA: IT Procurement team quản lý tất cả license. Nhắc nhở sẽ được gửi 30 ngày trước khi hết hạn."
20,it_helpdesk_faq_3,support/helpdesk-faq.md,IT,Section 4: Thiết bị và phần cứng,2026-01-20,internal,"Q: Laptop mới được cấp sau bao lâu khi vào công ty?\nA: Laptop được cấp trong ngày onboarding đầu tiên. Nếu có vấn đề, liên hệ HR hoặc IT Admin.\n\nQ: Laptop bị hỏng phải báo cáo như thế nào?\nA: Tạo ticket P2 hoặc P3 tùy mức độ nghiêm trọng. Mang thiết bị đến IT Room (tầng 3) để kiểm tra."
21,it_helpdesk_faq_4,support/helpdesk-faq.md,IT,Section 5: Email và lịch,2026-01-20,internal,"Q: Hộp thư đến đầy, phải làm gì?\nA: Xóa email cũ hoặc yêu cầu tăng dung lượng qua ticket IT-ACCESS. Dung lượng tiêu chuẩn là 50GB.\n\nQ: Tôi không nhận được email từ bên ngoài?\nA: Kiểm tra thư mục Spam trước. Nếu vẫn không có, tạo ticket P2 kèm địa chỉ email gửi và thời gian gửi."
22,it_helpdesk_faq_5,support/helpdesk-faq.md,IT,Section 6: Liên hệ IT Helpdesk,2026-01-20,internal,"Hotline: ext. 9000 (8:00 - 18:00, Thứ 2 - Thứ 6)\nEmail: helpdesk@company.internal\nJira: project IT-SUPPORT\nSlack: #it-helpdesk\nEmergency (ngoài giờ): ext. 9999"
23,policy_refund_v4_0,policy/refund-v4.pdf,CS,Điều 1: Phạm vi áp dụng,2026-02-01,internal,Chính sách này áp dụng cho tất cả các đơn hàng được đặt trên hệ thống nội bộ kể từ ngày 01/02/2026.\nCác đơn hàng đặt trước ngày có hiệu lực sẽ áp dụng theo chính sách hoàn tiền phiên bản 3.
24,policy_refund_v4_1,policy/refund-v4.pdf,CS,Điều 2: Điều kiện được hoàn tiền,2026-02-01,internal,"Khách hàng được quyền yêu cầu hoàn tiền khi đáp ứng đủ các điều kiện sau:\n- Sản phẩm bị lỗi do nhà sản xuất, không phải do người dùng.\n- Yêu cầu được gửi trong vòng 7 ngày làm việc kể từ thời điểm xác nhận đơn hàng.\n- Đơn hàng chưa được sử dụng hoặc chưa bị mở seal."
25,policy_refund_v4_2,policy/refund-v4.pdf,CS,Điều 3: Điều kiện áp dụng và ngoại lệ,2026-02-01,internal,"Hoàn tiền — Điều kiện áp dụng:\nYêu cầu được gửi trong vòng 7 ngày kể từ thời điểm xác nhận đơn hàng.\n\nNgoại lệ không được hoàn tiền:\n- Sản phẩm thuộc danh mục hàng kỹ thuật số (license key, subscription).\n- Đơn hàng đã áp dụng mã giảm giá đặc biệt theo chương trình khuyến mãi Flash Sale.\n- Sản phẩm đã được kích hoạt hoặc đăng ký tài khoản."
26,policy_refund_v4_3,policy/refund-v4.pdf,CS,Điều 4: Quy trình xử lý yêu cầu hoàn tiền,2026-02-01,internal,"Bước 1: Khách hàng gửi yêu cầu qua hệ thống ticket nội bộ với category ""Refund Request"".\nBước 2: CS Agent xem xét trong vòng 1 ngày làm việc và xác nhận điều kiện đủ điều kiện.\nBước 3: Nếu đủ điều kiện, chuyển yêu cầu sang Finance Team để xử lý hoàn tiền.\nBước 4: Finance Team xử lý trong 3-5 ngày làm việc và thông báo kết quả cho khách hàng."
27,policy_refund_v4_4,policy/refund-v4.pdf,CS,Điều 5: Hình thức hoàn tiền,2026-02-01,internal,- Hoàn tiền qua phương thức thanh toán gốc: áp dụng trong 100% trường hợp đủ điều kiện.\n- Hoàn tiền qua credit nội bộ (store credit): khách hàng có thể chọn nhận store credit thay thế với giá trị 110% so với số tiền hoàn.
28,policy_refund_v4_5,policy/refund-v4.pdf,CS,Điều 6: Liên hệ và hỗ trợ,2026-02-01,internal,"Email: cs-refund@company.internal\nHotline nội bộ: ext. 1234\nGiờ làm việc: Thứ 2 - Thứ 6, 8:00 - 17:30"

In [10]:
results_with_vec = col.get(include=["documents", "metadatas", "embeddings"])

df_vec = pd.DataFrame(results_with_vec["metadatas"])
df_vec["text"] = results_with_vec["documents"]
df_vec["chunk_id"] = results_with_vec["ids"]
df_vec["embedding_dim"] = [len(e) for e in results_with_vec["embeddings"]]
df_vec["embedding_preview"] = [str(e[:5]) + "..." for e in results_with_vec["embeddings"]]

# ✅ Fix: lưu từng vector riêng lẻ dưới dạng object
import numpy as np
df_vec["embedding_full"] = pd.Series(
    [np.array(e) for e in results_with_vec["embeddings"]],
    dtype=object
)

df_vec[["chunk_id", "source", "section", "text", "embedding_dim", "embedding_preview"]]

,chunk_id,source,section,text,embedding_dim,embedding_preview
0,hr_leave_policy_0,hr/leave-policy-2026.pdf,Phần 1: Các loại nghỉ phép,1.1 Nghỉ phép năm (Annual Leave):\n- Số ngày: 12 ngày/năm cho nhân viên dưới 3 năm kinh nghiệm.\n- Số ngày: 15 ngày/năm cho nhân viên từ 3-5 năm kinh nghiệm.\n- Số ngày: 18 ngày/năm cho nhân viên trên 5 năm kinh nghiệm.\n- Chuyển năm sau: Tối đa 5 ngày phép năm chưa dùng được chuyển sang năm tiếp theo.\n\n1.2 Nghỉ ốm (Sick Leave):\n- Số ngày: 10 ngày/năm có trả lương.\n- Yêu cầu: Thông báo cho Line Manager trước 9:00 sáng ngày nghỉ.\n- Nếu nghỉ trên 3 ngày liên tiếp: Cần giấy tờ y tế từ bệnh viện.\n\n1.3 Nghỉ thai sản:\n- Nghỉ sinh con: 6 tháng theo quy định Luật Lao động.\n- Nghỉ nuôi con nhỏ: 1 tiếng/ngày trong 12 tháng đầu sau sinh.\n\n1.4 Nghỉ lễ tết:\nTheo lịch nghỉ lễ quốc gia do HR công bố hàng năm vào tháng 12.,768,[-0.10544657 -0.35803926 0.0925934 0.07829947 -0.05705883]...
1,hr_leave_policy_1,hr/leave-policy-2026.pdf,Phần 2: Quy trình xin nghỉ phép,Bước 1: Nhân viên gửi yêu cầu nghỉ phép qua hệ thống HR Portal (https://hr.company.internal) ít nhất 3 ngày làm việc trước ngày nghỉ.\nBước 2: Line Manager phê duyệt hoặc từ chối trong vòng 1 ngày làm việc.\nBước 3: Nhân viên nhận thông báo qua email sau khi được phê duyệt.\n\nTrường hợp khẩn cấp: Có thể gửi yêu cầu muộn hơn nhưng phải được Line Manager đồng ý qua tin nhắn trực tiếp.,768,[0.0228693 0.07433899 0.38889948 0.08142848 0.04502574]...
2,hr_leave_policy_2,hr/leave-policy-2026.pdf,Phần 3: Chính sách làm thêm giờ,3.1 Điều kiện làm thêm:\nLàm thêm giờ phải được Line Manager phê duyệt trước bằng văn bản.\n\n3.2 Hệ số lương làm thêm:\n- Ngày thường: 150% lương giờ tiêu chuẩn.\n- Ngày cuối tuần: 200% lương giờ tiêu chuẩn.\n- Ngày lễ: 300% lương giờ tiêu chuẩn.,768,[ 0.14177014 -0.31538245 0.10786015 0.03202451 0.12559462]...
3,hr_leave_policy_3,hr/leave-policy-2026.pdf,Phần 4: Remote work policy,4.1 Điều kiện remote:\n- Nhân viên sau probation period có thể làm remote tối đa 2 ngày/tuần.\n- Team Lead phải phê duyệt lịch remote qua HR Portal.\n- Ngày onsite bắt buộc: Thứ 3 và Thứ 5 theo lịch team.\n\n4.2 Yêu cầu kỹ thuật khi remote:\n- Kết nối VPN bắt buộc khi làm việc với hệ thống nội bộ.\n- Camera bật trong các cuộc họp team.,768,[-0.10312014 -0.22338301 0.41928133 0.20461178 0.18991202]...
4,hr_leave_policy_4,hr/leave-policy-2026.pdf,Phần 5: Liên hệ HR,"Email: hr@company.internal\nHotline: ext. 2000\nHR Portal: https://hr.company.internal\nGiờ làm việc: Thứ 2 - Thứ 6, 8:30 - 17:30",768,[0.13709934 0.05276928 0.103631 0.08528698 0.18041082]...
5,access_control_sop_0,it/access-control-sop.md,Section 1: Phạm vi và mục đích,"Tài liệu này quy định quy trình cấp phép truy cập vào các hệ thống nội bộ của công ty.\nÁp dụng cho tất cả nhân viên, contractor, và third-party vendor.",768,[ 0.14847013 -0.22176048 -0.03724947 0.03500473 -0.0334909 ]...
6,access_control_sop_1,it/access-control-sop.md,Section 2: Phân cấp quyền truy cập,"Level 1 — Read Only:\nÁp dụng cho: Tất cả nhân viên mới trong 30 ngày đầu.\nPhê duyệt: Line Manager.\nThời gian xử lý: 1 ngày làm việc.\n\nLevel 2 — Standard Access:\nÁp dụng cho: Nhân viên chính thức đã qua thử việc.\nPhê duyệt: Line Manager + IT Admin.\nThời gian xử lý: 2 ngày làm việc.\n\nLevel 3 — Elevated Access:\nÁp dụng cho: Team Lead, Senior Engineer, Manager.\nPhê duyệt: Line Manager + IT Admin + IT Security.\nThời gian xử lý: 3 ngày làm việc.\n\nLevel 4 — Admin Access:\nÁp dụng cho: DevOps, SRE, IT Admin.\nPhê duyệt: IT Manager + CISO.\nThời gian xử lý: 5 ngày làm việc.\nYêu cầu thêm: Training bắt buộc về security policy.",768,[ 0.31125882 -0.11506814 -0.05914717 0.05297611 -0.00125431]...
7,access_control_sop_2,it/access-control-sop.md,Section 3: Quy trình yêu cầu cấp quyền,Bước 1: Nhân viên tạo Access Request ticket trên Jira (project IT-ACCESS).\nBước 2: Line Manager phê duyệt yêu cầu trong 1 ngày làm việc.\nBước 3: IT Admin kiểm tra compliance và cấp quyền.\nBước 4: IT Security review với Level 3 và Level 4.\nBước 5: Nhân viên nhận thông báo qua email khi quyền được cấp.,768,[-0.09225848 -0.0948665 0.15686622 0.00055686 0.06325274]...
8,access_control_sop_3,it/access-control-sop.md,Section 4: Escalation khi cần thay đổi quyền hệ thống,"Escalation chỉ áp dụng khi cần thay đổi quyền hệ thống ngoài quy trình thông thường.\nVí dụ: Khẩn cấp trong sự cố P1, cần cấp quyền tạm thời để fix incident.\n\nQuy trình escalation khẩn cấp:\n1. On-call IT Admin có thể cấp quyền tạm thời (max 24 giờ) sau khi được Tech Lead phê duyệt bằng lời.\n2. Sau 24 giờ, phải có ticket chính thức hoặc quyền bị thu hồi tự động.\n3. Mọi quyền tạm thời phải được ghi log vào hệ thống Security Audit.",768,[-0.01002593 0.07361636 0.28335935 0.26645577 0.07299702]...
9,access_control_sop_4,it/access-control-sop.md,Section 5: Thu hồi quyền truy cập,Quyền phải được thu hồi trong các trường hợp:\n- Nhân viên nghỉ việc: Thu hồi ngay trong ngày cuối.\n- Hết hạn contract: Thu hồi đúng ngày hết hạn.\n- Chuyển bộ phận: Điều chỉnh trong 3 ngày làm việc.,768,[-0.14953387 -0.03613087 0.37037548 0.08064362 -0.14026301]...
10,access_control_sop_5,it/access-control-sop.md,Section 6: Audit và review định kỳ,IT Security thực hiện access review mỗi 6 tháng.\nMọi bất thường phải được báo cáo lên CISO trong vòng 24 giờ.,768,[ 0.16012287 -0.27084357 -0.06992339 0.06312873 0.05121296]...
11,access_control_sop_6,it/access-control-sop.md,Section 7: Công cụ liên quan,Ticket system: Jira (project IT-ACCESS)\nIAM system: Okta\nAudit log: Splunk\nEmail: it-access@company.internal,768,[ 0.06979214 0.09782618 0.01106036 -0.24536195 -0.05500907]...
12,sla_p1_2026_0,support/sla-p1-2026.pdf,Phần 1: Định nghĩa mức độ ưu tiên,"P1 — CRITICAL (Khẩn cấp):\nĐịnh nghĩa: Sự cố ảnh hưởng toàn bộ hệ thống production, không có workaround.\nVí dụ: Database sập, API gateway down, toàn bộ người dùng không thể đăng nhập.\n\nP2 — HIGH (Nghiêm trọng):\nĐịnh nghĩa: Sự cố ảnh hưởng một phần hệ thống, có workaround tạm thời.\nVí dụ: Một số tính năng không hoạt động, ảnh hưởng một nhóm người dùng.\n\nP3 — MEDIUM (Trung bình):\nĐịnh nghĩa: Lỗi ảnh hưởng không đáng kể, người dùng vẫn làm việc được.\n\nP4 — LOW (Thấp):\nĐịnh nghĩa: Yêu cầu cải tiến, gợi ý, hoặc lỗi giao diện nhỏ.",768,[ 0.09678533 -0.13551576 -0.16185611 0.07614604 -0.09657642]...
13,sla_p1_2026_1,support/sla-p1-2026.pdf,Phần 2: SLA theo mức độ ưu tiên,"Ticket P1:\n- Phản hồi ban đầu (first response): 15 phút kể từ khi ticket được tạo.\n- Xử lý và khắc phục (resolution): 4 giờ.\n- Escalation: Tự động escalate lên Senior Engineer nếu không có phản hồi trong 10 phút.\n- Thông báo stakeholder: Ngay khi nhận ticket, update mỗi 30 phút cho đến khi resolve.\n\nTicket P2:\n- Phản hồi ban đầu: 2 giờ.\n- Xử lý và khắc phục: 1 ngày làm việc.\n- Escalation: Tự động escalate sau 90 phút không có phản hồi.\n\nTicket P3:\n- Phản hồi ban đầu: 1 ngày làm việc.\n- Xử lý và khắc phục: 5 ngày làm việc.\n\nTicket P4:\n- Phản hồi ban đầu: 3 ngày làm việc.\n- Xử lý và khắc phục: Theo sprint cycle (thông thường 2-4 tuần).",768,[-0.16594417 -0.1858032 0.45860824 0.03490259 0.08437014]...
14,sla_p1_2026_2,support/sla-p1-2026.pdf,Phần 3: Quy trình xử lý sự cố P1,"Bước 1: Tiếp nhận\nOn-call engineer nhận alert hoặc ticket, xác nhận severity trong 5 phút.\n\nBước 2: Thông báo\nGửi thông báo tới Slack #incident-p1 và email incident@company.internal ngay lập tức.\n\nBước 3: Triage và phân công\nLead Engineer phân công engineer xử lý trong 10 phút.\n\nBước 4: Xử lý\nEngineer cập nhật tiến độ lên ticket mỗi 30 phút. Nếu cần hỗ trợ thêm, escalate ngay.\n\nBước 5: Resolution\nSau khi khắc phục, viết incident report trong vòng 24 giờ.",768,[ 4.28531384e-05 -1.17850505e-01 2.95319647e-01 -3.56876515e-02\n -2.68171355e-02]...
15,sla_p1_2026_3,support/sla-p1-2026.pdf,Phần 4: Công cụ và kênh liên lạc,"Ticket system: Jira (project IT-SUPPORT)\nSlack channel: #incident-p1, #incident-p2\nPagerDuty: Tự động nhắn on-call khi P1 ticket mới\nHotline on-call: ext. 9999 (24/7)",768,[ 0.0399592 -0.03322219 0.05558755 -0.213072 -0.08890483]...
16,sla_p1_2026_4,support/sla-p1-2026.pdf,Phần 5: Lịch sử phiên bản,v2026.1 (2026-01-15): Cập nhật SLA P1 resolution từ 6 giờ xuống 4 giờ.\nv2025.3 (2025-09-01): Thêm quy trình escalation tự động.\nv2025.1 (2025-03-01): Phiên bản đầu tiên.,768,[-0.14206807 -0.16283327 0.32469574 0.11668485 -0.0621969 ]...
17,it_helpdesk_faq_0,support/helpdesk-faq.md,Section 1: Tài khoản và mật khẩu,"Q: Tôi quên mật khẩu, phải làm gì?\nA: Truy cập https://sso.company.internal/reset hoặc liên hệ Helpdesk qua ext. 9000. Mật khẩu mới sẽ được gửi qua email công ty trong vòng 5 phút.\n\nQ: Tài khoản bị khóa sau bao nhiêu lần đăng nhập sai?\nA: Tài khoản bị khóa sau 5 lần đăng nhập sai liên tiếp. Để mở khóa, liên hệ IT Helpdesk hoặc tự reset qua portal SSO.\n\nQ: Mật khẩu cần thay đổi định kỳ không?\nA: Có. Mật khẩu phải được thay đổi mỗi 90 ngày. Hệ thống sẽ nhắc nhở 7 ngày trước khi hết hạn.",768,[ 0.14153339 -0.04997469 0.07567544 -0.1799207 -0.03911776]...
18,it_helpdesk_faq_1,support/helpdesk-faq.md,Section 2: VPN và kết nối từ xa,"Q: Phần mềm VPN nào công ty dùng?\nA: Công ty sử dụng Cisco AnyConnect. Download tại https://vpn.company.internal/download.\n\nQ: Tôi bị mất kết nối VPN liên tục, phải làm gì?\nA: Kiểm tra kết nối Internet trước. Nếu vẫn lỗi, tạo ticket P3 với log file VPN đính kèm.\n\nQ: VPN có giới hạn số thiết bị không?\nA: Mỗi tài khoản được kết nối VPN trên tối đa 2 thiết bị cùng lúc.",768,[0.03353329 0.07093845 0.14833668 0.06579521 0.00466183]...
19,it_helpdesk_faq_2,support/helpdesk-faq.md,Section 3: Phần mềm và license,"Q: Tôi cần cài phần mềm mới, phải làm gì?\nA: Gửi yêu cầu qua Jira project IT-SOFTWARE. Line Manager phải phê duyệt trước khi IT cài đặt.\n\nQ: Ai chịu trách nhiệm gia hạn license phần mềm?\nA: IT Procurement team quản lý tất cả license. Nhắc nhở sẽ được gửi 30 ngày trước khi hết hạn.",768,[ 0.03432349 0.10394348 0.32698861 -0.16463539 -0.33261585]...
20,it_helpdesk_faq_3,support/helpdesk-faq.md,Section 4: Thiết bị và phần cứng,"Q: Laptop mới được cấp sau bao lâu khi vào công ty?\nA: Laptop được cấp trong ngày onboarding đầu tiên. Nếu có vấn đề, liên hệ HR hoặc IT Admin.\n\nQ: Laptop bị hỏng phải báo cáo như thế nào?\nA: Tạo ticket P2 hoặc P3 tùy mức độ nghiêm trọng. Mang thiết bị đến IT Room (tầng 3) để kiểm tra.",768,[ 0.05560159 -0.11079574 0.03143943 -0.133056 -0.15943603]...
21,it_helpdesk_faq_4,support/helpdesk-faq.md,Section 5: Email và lịch,"Q: Hộp thư đến đầy, phải làm gì?\nA: Xóa email cũ hoặc yêu cầu tăng dung lượng qua ticket IT-ACCESS. Dung lượng tiêu chuẩn là 50GB.\n\nQ: Tôi không nhận được email từ bên ngoài?\nA: Kiểm tra thư mục Spam trước. Nếu vẫn không có, tạo ticket P2 kèm địa chỉ email gửi và thời gian gửi.",768,[0.00298367 0.08058554 0.19279976 0.14623424 0.08983229]...
22,it_helpdesk_faq_5,support/helpdesk-faq.md,Section 6: Liên hệ IT Helpdesk,"Hotline: ext. 9000 (8:00 - 18:00, Thứ 2 - Thứ 6)\nEmail: helpdesk@company.internal\nJira: project IT-SUPPORT\nSlack: #it-helpdesk\nEmergency (ngoài giờ): ext. 9999",768,[ 0.00802994 0.06754151 0.16222616 0.12979808 -0.28659001]...
23,policy_refund_v4_0,policy/refund-v4.pdf,Điều 1: Phạm vi áp dụng,Chính sách này áp dụng cho tất cả các đơn hàng được đặt trên hệ thống nội bộ kể từ ngày 01/02/2026.\nCác đơn hàng đặt trước ngày có hiệu lực sẽ áp dụng theo chính sách hoàn tiền phiên bản 3.,768,[ 0.0417119 -0.04090064 0.18622652 0.3636561 0.19569337]...
24,policy_refund_v4_1,policy/refund-v4.pdf,Điều 2: Điều kiện được hoàn tiền,"Khách hàng được quyền yêu cầu hoàn tiền khi đáp ứng đủ các điều kiện sau:\n- Sản phẩm bị lỗi do nhà sản xuất, không phải do người dùng.\n- Yêu cầu được gửi trong vòng 7 ngày làm việc kể từ thời điểm xác nhận đơn hàng.\n- Đơn hàng chưa được sử dụng hoặc chưa bị mở seal.",768,[ 0.0066751 -0.3015976 0.59278101 -0.15907001 -0.11062586]...
25,policy_refund_v4_2,policy/refund-v4.pdf,Điều 3: Điều kiện áp dụng và ngoại lệ,"Hoàn tiền — Điều kiện áp dụng:\nYêu cầu được gửi trong vòng 7 ngày kể từ thời điểm xác nhận đơn hàng.\n\nNgoại lệ không được hoàn tiền:\n- Sản phẩm thuộc danh mục hàng kỹ thuật số (license key, subscription).\n- Đơn hàng đã áp dụng mã giảm giá đặc biệt theo chương trình khuyến mãi Flash Sale.\n- Sản phẩm đã được kích hoạt hoặc đăng ký tài khoản.",768,[ 0.13716745 -0.06486011 0.31111082 -0.0867772 -0.0560483 ]...
26,policy_refund_v4_3,policy/refund-v4.pdf,Điều 4: Quy trình xử lý yêu cầu hoàn tiền,"Bước 1: Khách hàng gửi yêu cầu qua hệ thống ticket nội bộ với category ""Refund Request"".\nBước 2: CS Agent xem xét trong vòng 1 ngày làm việc và xác nhận điều kiện đủ điều kiện.\nBước 3: Nếu đủ điều kiện, chuyển yêu cầu sang Finance Team để xử lý hoàn tiền.\nBước 4: Finance Team xử lý trong 3-5 ngày làm việc và thông báo kết quả cho khách hàng.",768,[-0.11533873 0.01257789 0.36061585 -0.13437869 0.05562056]...
27,policy_refund_v4_4,policy/refund-v4.pdf,Điều 5: Hình thức hoàn tiền,- Hoàn tiền qua phương thức thanh toán gốc: áp dụng trong 100% trường hợp đủ điều kiện.\n- Hoàn tiền qua credit nội bộ (store credit): khách hàng có thể chọn nhận store credit thay thế với giá trị 110% so với số tiền hoàn.,768,[ 0.18566436 -0.32186076 0.18181509 0.22306871 -0.01425798]...
28,policy_refund_v4_5,policy/refund-v4.pdf,Điều 6: Liên hệ và hỗ trợ,"Email: cs-refund@company.internal\nHotline nội bộ: ext. 1234\nGiờ làm việc: Thứ 2 - Thứ 6, 8:00 - 17:30",768,[0.08900857 0.14517725 0.09972091 0.05966996 0.23663482]...

In [8]:
# Ví dụ: chỉ xem chunks của CS
df[df["department"] == "CS"]

,chunk_id,source,department,section,effective_date,access,text
23,policy_refund_v4_0,policy/refund-v4.pdf,CS,Điều 1: Phạm vi áp dụng,2026-02-01,internal,Chính sách này áp dụng cho tất cả các đơn hàng được đặt trên hệ thống nội bộ kể từ ngày 01/02/2026.\nCác đơn hàng đặt trước ngày có hiệu lực sẽ áp dụng theo chính sách hoàn tiền phiên bản 3.
24,policy_refund_v4_1,policy/refund-v4.pdf,CS,Điều 2: Điều kiện được hoàn tiền,2026-02-01,internal,"Khách hàng được quyền yêu cầu hoàn tiền khi đáp ứng đủ các điều kiện sau:\n- Sản phẩm bị lỗi do nhà sản xuất, không phải do người dùng.\n- Yêu cầu được gửi trong vòng 7 ngày làm việc kể từ thời điểm xác nhận đơn hàng.\n- Đơn hàng chưa được sử dụng hoặc chưa bị mở seal."
25,policy_refund_v4_2,policy/refund-v4.pdf,CS,Điều 3: Điều kiện áp dụng và ngoại lệ,2026-02-01,internal,"Hoàn tiền — Điều kiện áp dụng:\nYêu cầu được gửi trong vòng 7 ngày kể từ thời điểm xác nhận đơn hàng.\n\nNgoại lệ không được hoàn tiền:\n- Sản phẩm thuộc danh mục hàng kỹ thuật số (license key, subscription).\n- Đơn hàng đã áp dụng mã giảm giá đặc biệt theo chương trình khuyến mãi Flash Sale.\n- Sản phẩm đã được kích hoạt hoặc đăng ký tài khoản."
26,policy_refund_v4_3,policy/refund-v4.pdf,CS,Điều 4: Quy trình xử lý yêu cầu hoàn tiền,2026-02-01,internal,"Bước 1: Khách hàng gửi yêu cầu qua hệ thống ticket nội bộ với category ""Refund Request"".\nBước 2: CS Agent xem xét trong vòng 1 ngày làm việc và xác nhận điều kiện đủ điều kiện.\nBước 3: Nếu đủ điều kiện, chuyển yêu cầu sang Finance Team để xử lý hoàn tiền.\nBước 4: Finance Team xử lý trong 3-5 ngày làm việc và thông báo kết quả cho khách hàng."
27,policy_refund_v4_4,policy/refund-v4.pdf,CS,Điều 5: Hình thức hoàn tiền,2026-02-01,internal,- Hoàn tiền qua phương thức thanh toán gốc: áp dụng trong 100% trường hợp đủ điều kiện.\n- Hoàn tiền qua credit nội bộ (store credit): khách hàng có thể chọn nhận store credit thay thế với giá trị 110% so với số tiền hoàn.
28,policy_refund_v4_5,policy/refund-v4.pdf,CS,Điều 6: Liên hệ và hỗ trợ,2026-02-01,internal,"Email: cs-refund@company.internal\nHotline nội bộ: ext. 1234\nGiờ làm việc: Thứ 2 - Thứ 6, 8:00 - 17:30"

In [9]:
print(f"Tổng chunks: {len(df)}\n")
print(df.groupby("department").size().rename("số chunks").to_string())

Tổng chunks: 29

department
CS              6
HR              5
IT             11
IT Security     7